mysql:
  user: user
  port: 3306
  password: pass
  host: localhost
  database: database
logging:
  debug: false
  access-key: key
server:
  name: 'Server'
  short: 'S'
announcement:
  interval: 600
  messages: {}
teleport:
  randomtp-radius: 100
  randomtp-blacklist: {}
  request-timeout: 30
points:
  join: 50
  vote: 1
  daily: 2
market:
  max-time: 604800
  max-trades: 5
reminder:
  vote:
    interval: 1800
    messages: {}
  daily:
    interval: 1800
    messages: {}
temporary-world:
servers: {}
rules: {}
ranks: {}
information: ()
livemap: {}
vote: {}
donate: {}
worlds: {}
warps: {}
rewards: {}
challenges: {}
trades: {}
teams: {}
gui: {}